name: Release Asset

on:
  # When Release Pull Request is merged
  push:
    branches:
      - master
      - feature-*
      - hotfix-*
  pull_request:
    branches:
      - master
      - feature-*
      - hotfix-*
    types: [closed]

jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Should it be skipped?
        env:
          COMMIT_FILTER: 'chore(release)'
          CI_STAGE_NAME: 'CHECK_COMMIT'
          CURRENT_BRANCH: ${{ github.ref }}
        run: |
          bash etc/deployments/cd.sh

  do-linter:
    needs: check-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com/'

      - name: Install NPM Cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Do linter
        env:
          CI_STAGE_NAME: 'TEST'
        run: |
          bash etc/deployments/cd.sh

  publish-gpr:
    needs: do-linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          token: ${{ secrets.TOKEN_BUILD }}
          fetch-depth: 0

      - uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com/'

      - name: Install NPM Cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Ensure access
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN_BUILD }}
        run: npm whoami --registry https://npm.pkg.github.com/

      - name: Config git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "irfanandriansyah10@gmail.com"

      - name: Bump versions and publish packages
        env:
          CI_STAGE_NAME: 'BUILD'
          CURRENT_BRANCH: ${{ github.ref }}
          LERNA_ACTION: '--create-release github --message "chore(release): publish"'
          GH_TOKEN: ${{ secrets.TOKEN_BUILD }}
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN_BUILD }}
        run: |
          bash etc/deployments/cd.sh
