name: Continuos Integration

on: [push, pull_request]

jobs:
    publish-gpr:
        name: Do Linter
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: 'https://npm.pkg.github.com/'

            - name: Install Depedency
              run: |
                  yarn global add lerna
                  yarn

            - name: Do Linter
              run: yarn run test
