name: Continuos Integration

on: pull_request

jobs:
  do-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com/'

      - name: Install NPM Cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Do linter
        env:
          CI_STAGE_NAME: 'TEST'
        run: |
          bash etc/deployments/cd.sh
