name: Release Asset

on:
    push:
        branches:
            - main
    pull_request:
        branches-ignore:
            - main

jobs:
    do-linter:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: 'https://npm.pkg.github.com/'

            - name: Install Depedency
              run: |
                  yarn global add lerna
                  yarn

            - name: Do Linter
              run: yarn run test
    publish-gpr:
        needs: do-linter
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  token: ${{ secrets.TOKEN_BUILD }}
                  fetch-depth: 0

            - uses: webfactory/ssh-agent@v0.5.1
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: 'https://npm.pkg.github.com/'

            - name: Ensure access
              run: npm whoami --registry https://npm.pkg.github.com/
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.TOKEN_BUILD }}

            - name: Config git user
              run: |
                  git config --global user.name "${{ github.actor }}"
                  git config --global user.email "irfanandriansyah10@gmail.com"

            - name: Bump versions and publish packages
              run: |
                  yarn
                  yarn global add lerna
                  yarn run version:ci
                  yarn run publish:ci
              env:
                  GH_TOKEN: ${{ secrets.TOKEN_BUILD }}
                  NODE_AUTH_TOKEN: ${{ secrets.TOKEN_BUILD }}
